# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  default:
      - step:
          name: 'Build code'
          script:
            - npm cache clean -f
            - npm cache verify
            - npm install
            - npm run build
            - echo "Build Code Successful"
  branches:
    master:
      - step:
          name: 'Build code'
          script:
            - npm cache clean -f
            - npm cache verify
            - npm install
            - npm run build:dev
            - echo "Build Code to Master Successful"

    release/staging:
      - step:
          name: 'Build code'
          script:
              - echo "Build Code to Staging Successful"

    release/production:
      - step:
          name: 'Build code'
          script:
              - echo "Build Code to Production Successful"